# LLM 配置
llm {
  google-api-key = ${?GOOGLE_API_KEY}
  google-base-url = "https://generativelanguage.googleapis.com"
  deep-seek-api-key = ${?DEEP_SEEK_API_KEY}
  deep-seek-base-url = "https://api.deepseek.com"
  minimax-coding-plan-key = ${?MINIMAX_CODING_PLAN_KEY}
  minimax-base-url = "https://api.minimaxi.com"
  choice-model = ${CHOICE_MODEL}
}

# Embedding 配置
embedding {
  api-key = ${?EMBEDDING_API_KEY}
  provider = "bytedance"
}

# Search 配置
search {
  api-key = ${?SEARCH_API_KEY}
  provider = "exa"
}

# Browser 相关配置
browser {
  playwright-host = ${PLAYWRIGHT_HOST}
}

# 代理配置
proxy {
  http = ${?HTTP_PROXY}
  socks = ${?SOCKS_PROXY}
}

# OneBot QQ Bot 配置
//onebot {
//  bots = {
//    erii = {
//      ws = ""
//      token = ""
//      role-id = ""
//      groups = {
//        000 = {
//          admins = [000]
//        }
//      }
//    }
//  }
//}

# 群组配置
//groups {
//  debug-group-id = null
//  enable-groups = []
//  message-redirect-map = []
//}
