services:
  erii:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erii-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -Xms256m -Xmx256m -XX:MaxGCPauseMillis=200 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/erii/oom_heap.hprof  -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai
      - ERII_CORE_OPTS=-Dpf4j.pluginsDir=./conf/plugins -Dconfig.plugin.dir=./conf/config -Dconfig.path=./conf/application.conf -Dconfig.souls.dir=./conf/souls -Dconfig.rules.dir=./conf/rules
    env_file:
      - ./conf/.env.local
    volumes:
      - ./conf:/erii/conf
      - ./store:/erii/store
    extra_hosts:
      - "hostmachine:host-gateway"
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8000:8000"

  playwright:
    image: mcr.microsoft.com/playwright:v1.57.0-noble
    container_name: playwright-server
    init: true
    user: pwuser
    working_dir: /home/pwuser
    ports:
      - "13001:3000"
    environment:
      #      - HTTP_PROXY=http://hostmachine:7890
      #      - HTTPS_PROXY=http://hostmachine:7890
      - NO_PROXY=localhost,127.0.0.1,hostmachine
    extra_hosts:
      - "hostmachine:host-gateway"
    command: >
      /bin/sh -c
      "npx -y playwright@1.57.0 run-server --port 3000 --host 0.0.0.0"


  napcat_0:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat-server-0
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6099:6099"
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    volumes:
      - ./napcat:/app/napcat/config
  napcat_1:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat-server-1
    restart: always
    ports:
      - "3010:3000"
      - "3011:3001"
      - "6199:6099"
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    volumes:
      - ./napcat:/app/napcat/config
  napcat_2:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat-server-2
    restart: always
    ports:
      - "3020:3000"
      - "3021:3001"
      - "6299:6099"
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    volumes:
      - ./napcat:/app/napcat/config
