services:
  erii:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erii-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    environment:
      - WEB_OPTS=--host 0.0.0.0 --port 8180
    volumes:
      - ./conf:/erii/conf
      - ./store:/erii/store
      - ./plugins:/erii/plugins
      - ./.conf:/erii/.conf
      - ./.erii:/erii/.erii
    extra_hosts:
      - "hostmachine:host-gateway"
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8000:8000"
      - "8180:8180"
