plugins {
  # 语音插件
  Speech {
    minimax-api-key = ${MINIMAX_API_KEY}
  }

  # 网易云音乐插件
  NetEaseMusic {
    api-base = ${NETEASE_MUSIC_API_BASE}
  }

  # Steam 插件
  SteamWatcher {
    api-key = ${STEAM_API_KEY}
    subscriptions = ${STEAM_SUBSCRIPTIONS}
  }

  # 图片插件
  ImageClient {
    google-api-key = ${GOOGLE_API_KEY}
  }
}
